run:
	gcc "int_list.c" "int_list_test.c" -o ./bin/int_list_test
	gcc "int_list.c" "int_list_test_hard.c" -o ./bin/int_list_test_hard
clean:
	rm -rf ./bin/int_list_test
	rm -rf ./bin/int_list_test_hard
